FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY *.mod *.sum ./
RUN go mod download

COPY . .
RUN rm -f app_aggregator_api

ENV CGO_ENABLED=0
RUN go build -a -o app_aggregator_api ./cmd/api/app_aggregator_api.go

FROM alpine:latest

RUN apk update && apk add --no-cache bash
WORKDIR /app
COPY --from=builder /app/app_aggregator_api /app/app_aggregator_api
CMD ["./app_aggregator_api"]